repos:
  # Custom hooks for project-specific rules
  - repo: local
    hooks:
      - id: protect-workflow-files
        name: Protect GitHub workflow files from modification
        entry: scripts/check-protected-files.sh
        language: script
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.github/workflows/(claude\.yml|claude-code-review\.yml)$
      - id: end-of-file-fixer
        exclude: ^\.github/workflows/(claude\.yml|claude-code-review\.yml)$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: [types-requests, types-cachetools]
        # Include tests for type checking to catch type errors early
        files: ^(src|tests)/.*\.py$
